### ISSUE TITLE
macOS Sonoma 14.4 broke macchanger, and ifconfig!? wtfh

### ISSUE THREAD

**Issue by artkiver** [shilch/macchanger#2]
I already submitted Feedback to Apple, but figured I would report things here too in case someone may discover a workaround.

macchanger worked without issues on macOS 14.3.1.

After updating to 14.4:

```
% sudo macchanger -r en0                         
Password:
INFO:    Type of interface is Wi-Fi. Will disassociate from any network.
WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.
ERROR:   This device / interface has no MAC address to set.

```

Worse, this doesn't seem to be unique to macchanger; ifconfig seems broken on macOS 14.4 Sonoma as well:

```
sudo ifconfig en0 ether 10:93:e8:37:38:39
ifconfig: ioctl (SIOCAIFADDR): Can't assign requested address
adomino@MBAm2starhikari ~ % sudo ifconfig en0 ether de:ad:be:ef:de:ad
ifconfig: ioctl (SIOCAIFADDR): Can't assign requested address
```

Tested as broken on two Apple Silicon devices which previously functioned OK with macchanger on 14.3.1.

**Comment by shilch** [comment]
Thanks for reporting this issue! I just upgraded to Sonoma 14.4.1 and can confirm the issue.  
This appears to be a problem with the `airport` command line tool as it doesn't associate from the network. You can manually disconnect from the Wi-Fi network and then run `macchanger` which works.

**Comment by shilch** [comment]
I tried to find an alternative to the `airport` command and came up with the following snippet that imitates `IO80211.framework`. Some information can also be found [here](https://newosxbook.com/articles/11208ellpA-II.html).

It would be great if you could test if this code correctly performs disassociation from Wi-Fi. If you have access to older versions of macOS it would also be great to have a positive sign that they are working there.

The below code can be compiled using `clang -o disassoc ./disassoc.c`.

```c
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/socket.h>

int main(int argc, char** argv) {
    int fd = socket(AF_INET, SOCK_DGRAM, 0);

    struct io80211_ioctl {
        char     ifname[16];
        uint64_t type;
        uint32_t length;
        void*    data;
    } ioc;
    strcpy(ioc.ifname, "en0");
    ioc.type = 22;
    ioc.length = 0;
    ioc.data = NULL;

    int res = ioctl(fd, 0x802869c8, &ioc);
    if(res == -1) {
        perror("ioctl");
        return res;
    }
    return 0;
}
```

**Comment by DarkNero69** [comment]
I have this same error, how do i fix this? I don't know what clang -o disassoc ./disassoc.c. even means?? I have turned my phone's wifi off and still this error comes :( what do i do? I really need this otherwise i can't do the things i've been doing for years.

**Comment by DarkNero69** [comment]
This is the error i get with wifi on or wifi off: 


INFO:    Type of interface is Wi-Fi. Will disassociate from any network.
WARNING: The airport command line tool is deprecated and will be removed in a future release.
For diagnosing Wi-Fi related issues, use the Wireless Diagnostics app or wdutil command line tool.
ERROR:   This device / interface has no MAC address to set.
rikishiro@Emins-MacBook-Air ~ %

**Comment by DarkNero69** [comment]
Please save meeeee i'm begging you :(

**Comment by DarkNero69** [comment]
Genius, how did you even pull this? Works now !

**Comment by shilch** [comment]
> Genius, how did you even pull this? Works now !

Great to hear that, @DarkNero69. Do you have the possibility to test the code on an older system?

**Comment by DarkNero69** [comment]
> > Genius, how did you even pull this? Works now !
> 
> Great to hear that, @DarkNero69. Do you have the possibility to test the code on an older system?

Hey, sorry for the delayed reply. Unfortunately i don't have another computer or any other system. I only got macbook air m1 :/ but this can easily be tested in public computers, though i don't have the time to hit up library at the moment haha

**Comment by aaronleetw** [comment]
@shilch The fix is tested to be working on my MBP 13-inch, 2020 running i5.
Be sure to run it with `sudo` though.

**Comment by shilch** [comment]
Thanks @aaronleetw, @DarkNero69!

I developed a new version that supports macOS Sonoma 14.4+ on branch `v0.2-draft`.

Please let me know if the new version does the job:

```bash
git clone -b v0.2-draft https://github.com/shilch/macchanger
cd macchanger
make
./macchanger
```

**Comment by aaronleetw** [comment]
@shilch Works on my end! Thank you for your work.

**Comment by DarkNero69** [comment]
@shilch It works for me too! I'm not very experienced with the terminal, but I managed to get it working hehe. Amazing work, thank you! It's much simpler and faster to use now =)

**Comment by artkiver** [comment]
> Thanks @aaronleetw, @DarkNero69!
> 
> I developed a new version that supports macOS Sonoma 14.4+ on branch `v0.2-draft`.
> 
> Please let me know if the new version does the job:
> 
> ```shell
> git clone -b v0.2-draft https://github.com/shilch/macchanger
> cd macchanger
> make
> ./macchanger
> ```

Thank you!

I've tested the new v0.2-draft branch on 14.3.1, 14.4 and 14.4.1 and it is functioning OK.

Attempting to build on OS X El Capitan 10.11.6 yields the following errors:

`make
macchanger.c:39:51: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
void interface_get_ether(const interface_t iface, ether_addr_t* ether);
                                                  ^~~~~~~~~~~~
                                                  user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:40:51: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
void interface_set_ether(interface_t iface, const ether_addr_t* ether);
                                                  ^~~~~~~~~~~~
                                                  user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:41:61: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
void interface_get_permanent_ether(const interface_t iface, ether_addr_t* eth...
                                                            ^~~~~~~~~~~~
                                                            user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:48:42: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
void change_mac(interface_t iface, const ether_addr_t* ether);
                                         ^~~~~~~~~~~~
                                         user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:50:19: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
void random_ether(ether_addr_t* ether);
                  ^~~~~~~~~~~~
                  user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:51:34: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
int ether_parse(const char* str, ether_addr_t* ether);
                                 ^~~~~~~~~~~~
                                 user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:52:35: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
const char* ether_to_string(const ether_addr_t* ether);
                                  ^~~~~~~~~~~~
                                  user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:65:5: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
    ether_addr_t ether;
    ^~~~~~~~~~~~
    user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:155:5: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
    ether_addr_t ether, permanent_ether;
    ^~~~~~~~~~~~
    user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:164:48: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
void change_mac(const interface_t iface, const ether_addr_t* new_ether) {
                                               ^~~~~~~~~~~~
                                               user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:165:5: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
    ether_addr_t permanent_ether, old_ether, current_ether;
    ^~~~~~~~~~~~
    user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:167:18: error: member reference base type 'const user_addr_t' (aka
      'const unsigned long long') is not a structure or union
    if (new_ether->octet[0] & 1) {
        ~~~~~~~~~^ ~~~~~
macchanger.c:194:19: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
void random_ether(ether_addr_t* ether) {
                  ^~~~~~~~~~~~
                  user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:204:35: error: member reference base type 'user_addr_t' (aka
      'unsigned long long') is not a structure or union
        ssize_t n = read(fd, ether->octet + (ETHER_ADDR_LEN - to_read), ...
                             ~~~~~^ ~~~~~
macchanger.c:213:10: error: member reference base type 'user_addr_t' (aka
      'unsigned long long') is not a structure or union
    ether->octet[0] &= 0xFE;
    ~~~~~^ ~~~~~
macchanger.c:219:34: error: unknown type name 'ether_addr_t'; did you mean
      'user_addr_t'?
int ether_parse(const char* str, ether_addr_t* ether) {
                                 ^~~~~~~~~~~~
                                 user_addr_t
/usr/include/i386/types.h:97:20: note: 'user_addr_t' declared here
typedef u_int64_t               user_addr_t;    
                                ^
macchanger.c:226:14: error: member reference base type 'user_addr_t' (aka
      'unsigned long long') is not a structure or union
        ether->octet[i] = 0;
        ~~~~~^ ~~~~~
macchanger.c:228:18: error: member reference base type 'user_addr_t' (aka
      'unsigned long long') is not a structure or union
            ether->octet[i] <<= 4;
            ~~~~~^ ~~~~~
macchanger.c:230:45: error: member reference base type 'user_addr_t' (aka
      'unsigned long long') is not a structure or union
            if(ch >= '0' && ch <= '9') ether->octet[i] |= (ch - '0');
                                       ~~~~~^ ~~~~~
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [macchanger] Error 1`

However, the previous macchanger.sh functions OK on El Capitan 10.11.6.

**Comment by artkiver** [comment]
I also noticed that on macOS versions with the v0.2-draft branch, when invoked without root privileges, it will fail to change the MAC address (expected behavior) but it will still disassociate from WiFi (I am not sure if this is desirable?).

**Comment by geek4what** [comment]
@shilch Hi there, the branch v0.2-draft didn't work on my macOS(Sonoma 14.4.1).
```
sudo ./macchanger -r en0
INFO:    Type of interface is Wi-Fi. Will disassociate from any network.
interface_set_ether: Can't assign requested address
```

**Comment by nilssonalex** [comment]
Thank you for this. It works with the wifi adapter on my M2 Macbook Air, Sonoma 14.5. But, it does not work with my Belkin USB-C ethernet adapter, i get the error message "interface_set_ether: Can't assign requested address". Any leads?

**Comment by DarkNero69** [comment]
Hello. Sorry i haven't been replied to anything yet. First of all, thank you so much for developing such an amazing thing! 

I haven't changed my mac address lately, but i just tested it by typing "sudo macchanger" to terminal. It seems like it works, managed to change to some random mac address. Thanks!

**Comment by shilch** [comment]
Sorry for not responding in a while.

@artkiver The compilation error occurs because the ether_addr_t did not exist in El Capitan. That should be an easy fix which I will add.

@geek4what Which device are you using? Is the en0 an Airport device?

@nilssonalex The tool uses the interface APIs provided by the operating system. If the network driver for this 3rd party device does not implement the possibility to change the mac address, there's nothing that macchanger can do. You would need a driver which has this feature.

**Comment by fharper** [comment]
The `v0.2-draft` is also working for me, thanks!

**Comment by geek4what** [comment]
> Sorry for not responding in a while.
> 
> @geek4what Which device are you using? Is the en0 an Airport device?
> 

wifi en0.
By the way, after upgrade to 14.5, it's work like a charm.

**Comment by johndekroon** [comment]
For wifi this works great. However, if I try to change the mac address of a wired network, I still get the following error:
sh-3.2# ./macchanger -m [mac] en17
interface_set_ether: Can't assign requested address

I use 14.5. The interface is listed as a USB 10/100/1000 device.

**Comment by dennis777** [comment]
> @shilch Hi there, the branch v0.2-draft didn't work on my macOS(Sonoma 14.4.1).
> 
> ```
> sudo ./macchanger -r en0
> INFO:    Type of interface is Wi-Fi. Will disassociate from any network.
> interface_set_ether: Can't assign requested address
> ```

It's because macchanger can't disassociate. Disconnect from wifi then run macchanger and it will work. Tested on M1 Max MBP running macOS 15 Sequoia beta

**Comment by dennis777** [comment]
> I tried to find an alternative to the `airport` command and came up with the following snippet that imitates `IO80211.framework`. Some information can also be found [here](https://newosxbook.com/articles/11208ellpA-II.html).
> 
> It would be great if you could test if this code correctly performs disassociation from Wi-Fi. If you have access to older versions of macOS it would also be great to have a positive sign that they are working there.
> 
> The below code can be compiled using `clang -o disassoc ./disassoc.c`.
> 
> ```c
> #include <stdint.h>
> #include <stdio.h>
> #include <string.h>
> #include <sys/ioctl.h>
> #include <sys/socket.h>
> 
> int main(int argc, char** argv) {
>     int fd = socket(AF_INET, SOCK_DGRAM, 0);
> 
>     struct io80211_ioctl {
>         char     ifname[16];
>         uint64_t type;
>         uint32_t length;
>         void*    data;
>     } ioc;
>     strcpy(ioc.ifname, "en0");
>     ioc.type = 22;
>     ioc.length = 0;
>     ioc.data = NULL;
> 
>     int res = ioctl(fd, 0x802869c8, &ioc);
>     if(res == -1) {
>         perror("ioctl");
>         return res;
>     }
>     return 0;
> }
> ```

Sadly this didn't work for me in macOS 15 beta (I never tried on macOS 14)

**Comment by ASolod82** [comment]
v0.2-draft, Macbook Pro 16 2021 M1 Pro

works fine for wifi en0, but for en4
```
sudo ./macchanger -r en4
interface_set_ether: Can't assign requested address
```

USB 10/100/1000 LAN:

  Bus:	USB
  Vendor Name:	Realtek
  Product Name:	USB 10/100/1000 LAN
  Vendor ID:	0x0bda
  Product ID:	0x8153
  USB Link Speed:	Up to 5 Gb/s
  Driver:	com.apple.DriverKit.AppleUserECM
  BSD Device Name:	en4
  MAC Address:	00:e0:4c:cc:3f:7d
  AVB Support:	No

**Comment by dennis777** [comment]
Just so I can understand correctly, with nothing plugged into your Mac (no hardwire internet connections, or network adapters), you **can** run `sudo./macchanger -r en0` while the MacBook is connected to a wireless network? Meaning it _disassociates_, changes the MAC address, and then reconnects?

Thanks

**Comment by ASolod82** [comment]
> Just so I can understand correctly, with nothing plugged into your Mac (no hardwire internet connections, or network adapters), you **can** run `sudo./macchanger -r en0` while the MacBook is connected to a wireless network? Meaning it _disassociates_, changes the MAC address, and then reconnects?
> 
> Thanks

<img width="819" alt="image" src="https://github.com/shilch/macchanger/assets/4346300/818a56fa-5650-4f0a-bdbd-c15fdbf38ac3">

**Comment by dennis777** [comment]
Were you connected to wifi on en0 before you ran the command? And what does it show you when you run en4?

**Comment by shilch** [comment]
@johndekroon @dennis777 @ASolod82 Thanks for your tests!

Can you please check if it works / there are errors for the following cases:
- Using the v0.2-draft version
- Using the master version but disassociating using this [snippet](https://github.com/shilch/macchanger/issues/2#issuecomment-2021397656)
- Using the master version but disassociating using the macOS UI

**Comment by dennis777** [comment]
Certainly! Here are the results tested on my 21 MacBook Pro M1 Max macOS 15.0 beta (shouldn't be any different for 14 as airport is deprecated there as well)

## Using the v0.2-draft version
**Result:** Does not disassociate from wifi, thus not changing the Mac address
<img width="514" alt="Screenshot 2024-07-08 at 10 12 14" src="https://github.com/shilch/macchanger/assets/25965937/ef8cae57-7c12-4c9a-b48b-216624cdbc49">
Manually disassociating, works just fine
<img width="517" alt="image" src="https://github.com/shilch/macchanger/assets/25965937/c109d55f-7fa5-4ef0-ab97-1ccc3b5561b1">
## Using the master version but disassociating using this [snippet](https://github.com/shilch/macchanger/issues/2#issuecomment-2021397656)
**Result:** does not disassociate but prints a message 
```
ioctl: Operation not supported on socket
```
So then as expected, the macchanger doesn't work because it doesn't disassociate using that snippet
<img width="695" alt="image" src="https://github.com/shilch/macchanger/assets/25965937/2c63014d-8ac2-40b2-9d2d-6004b1f8b399">

*seems like ioctl() call isn't working in disassoc.c*

## Using the master version but disassociating using the macOS UI
**Result:** Works perfectly fine
<img width="838" alt="image" src="https://github.com/shilch/macchanger/assets/25965937/b8a711a0-0829-4c78-be64-4f651fb3130b">

Hope this helps! Let me know if theres anything else I can test @shilch

**Comment by shilch** [comment]
Thanks @dennis777, I guess that Apple changed the interface to disassociate WiFi in one of the recent versions ("Operation not supported on socket" hints at an API change).
I am currently using 14.4.1 on M1 Pro and v0.2-draft works for me. User @geek4what had issues on 14.4.1 but upgrading to 14.5 fixed it, apparently. I assume that issue affects macOS 15.0+.  
The solution could be to implement the disassociation using IOKit instead of ioctl. The headers have been leaked [here](https://github.com/OpenIntelWireless/itlwm/tree/master/include/Airport). Once I'm less busy with university, I'll have a look at it.

**Comment by dennis777** [comment]
Ah okay I didn't know about this tool until after I updated to the beta. 

I will play around with those dumped headers and see if I can come up with anything in the meantime. But my experience with C is extremely limited. I wish I understood it better 😅 Thank you

**Comment by ldoench** [comment]
The `v0.2-draft` version worked fine.

Is it possible to make it installable by brew? 

Also the `git clone https://github.com/shilch/macchanger` command in the readme does not clone the `v0.2-draft.`. You should adjust it to `git clone -b v0.2-draft https://github.com/shilch/macchanger`

**Comment by dennis777** [comment]
> The `v0.2-draft` version worked fine.

Which model of Mac do you use and what version of macOS?

**Comment by kecinzer** [comment]
v0.2-draft not working for me. I have macOS 14.6.1 (23G93) and trying to change mac for my ehternet en6.

interface_set_ether: Can't assign requested address

**Comment by insert-zkm** [comment]
@kecinzer ive macos 14.6.1 For me [this](https://github.com/acrogenesis/macchanger/issues/16#issuecomment-2315141288) is worked perfectly. Shortly in the system settings create virtual interface for the actual interface and you could easily change mac address of virtual interface with `ifconfig`

**Comment by artkiver** [comment]
Still seemed to be functioning OK for me with 14.7.

However with macOS 15.0, it seems as if WiFi must be manually turned off, then back on, otherwise this error is encountered:

`macchanger -r en0
INFO:    Type of interface is Wi-Fi. Will disassociate from any network.
interface_set_ether: Can't assign requested address`

My guess is something changed with macOS Sequoia that broke the recent disassoc.c iteration?

**Comment by ncihnegn** [comment]
Need to manually disassociate to work on 15.2.

**Comment by shilch** [comment]
Hi everybody, sorry for the silence. I found a solution that automatically disassociates the wifi on newer macOS versions. Successfully tested on 15.2. I pushed the draft to a new branch `v0.2-draft2`.

Please let me know if this solution works for you and which version of macOS you are using.

```
git clone -b v0.2-draft2 https://github.com/shilch/macchanger
cd macchanger
make
sudo ./macchanger
```

**Comment by shilch** [comment]
> Is it possible to make it installable by brew?

@ldoench Once a working v0.2 is released I will make macchanger brew-installable.

**Comment by dennis777** [comment]
@shilch Confirmed it works 15.2! Thank you! Was the solution to rewrite it in Objective-C? Does apple not expose some API in C that is required to do the disassociation?

**Comment by shilch** [comment]
> Confirmed it works 15.2! Thank you! Was the solution to rewrite it in Objective-C? Does apple not expose some API in C that is required to do the disassociation?

@dennis777 Perfect! Actually, I just realized that I hardcoded the interface name for disassociation to `en0`. Fixed that.

The solution was to use CoreWLAN.framework, which is used by the WiFi dropdown in the status bar. The previous solution I posted reimplemented the disassociation from IO80211.framework, but that library seems to be broken as of some time ago.

CoreWLAN.framework does not expose a C API (officially). There are still traces of the Apple internal MobileWiFi.framework, but I believe it has been discontinued and I don't want to depend on it for macchanger to break again.

**Comment by dennis777** [comment]
> The solution was to use CoreWLAN.framework, which is used by the WiFi dropdown in the status bar. The previous solution I posted reimplemented the disassociation from IO80211.framework, but that library seems to be broken as of some time ago.

@shilch Makes sense Apple dropped IO80211 support. I believe I wonder if packet sniffing and frame injections are possible using the CoreWLAN.framework? Sniffing should be as there is a built in sniffer but I don't know If frames injections are. Do you think it's possible to for example send the deauth frames?

**Comment by dennis777** [comment]
> > I wonder if packet sniffing and frame injections are possible using the CoreWLAN.framework? Sniffing should be as there is a built in sniffer but I don't know If frames injections are. Do you think it's possible to for example send the deauth frames?
> 
> After having a short look, it looks like this is possible using a `/dev/bpfX` device (`man 4 bpf`). This technique is implemented by libpcap as `pcap_inject`. [This project](https://github.com/0x0XDev/JamWiFi) appears to offer what you are looking for.

That is the project I found years ago and am trying to rewrite but unfortunately no dice. I think apple may have disabled frame injections on a hardware level or something because the application doesn't even scan. Also it's not possible to even compile the project now due to some signing issue. Anyway thanks just was curious if you knew more.

**Comment by artkiver** [comment]
> Hi everybody, sorry for the silence. I found a solution that automatically disassociates the wifi on newer macOS versions. Successfully tested on 15.2. I pushed the draft to a new branch `v0.2-draft2`.
> 
> Please let me know if this solution works for you and which version of macOS you are using.
> 
> ```
> git clone -b v0.2-draft2 https://github.com/shilch/macchanger
> cd macchanger
> make
> sudo ./macchanger -r en0
> ```

I've confirmed that the v0.2-draft2 branch is working like a charm for me on 15.2 as well.

Unfortunately, last summer, someone broke into my car and stole two laptops (including a 2012 MacBook Pro I used for testing older OS versions) so I can't test more extensively at the moment.

I noticed someone else in the thread mentioned brew; and I am a MacPorts maintainer and have considered creating a Portfile for macchanger for MacPorts. Especially now that it seems to be functioning again without issue on the most -CURRENT non-beta OS release, I may look into that again (though others are welcome to contribute such things)!

I would generally dissuade security minded folks (as I assume most who are randomizing MAC addresses presumably are) from using brew _enitrely_ given that it has analytics on by default (information on how to disable them here: https://docs.brew.sh/Analytics) whereas MacPorts only has anonymous analytics gathered if users choose of their own volition to install mpstats (more information on that here: https://ports.macports.org/port/mpstats/)

Moreover, MacPorts was co-founded by jkh (Jordan Hubbard) who was a co-founder of FreeBSD and previously  "Director of Engineering of Unix Technologies" at Apple for a dozen some odd years and can be thought of as the complementary /usr/ports in a BSD system for OS X/macOS whereas brew is a bit NIH syndrome. In particular, MacPorts makes an effort to automate testing on many versions of macOS/OS X (going back to at least Leopard, though some users report still having success with it on Tiger) whereas brew only tends to focus on the current and last two macOS releases.

**Comment by PianoMan7** [comment]
> @shilch Confirmed it works 15.2! Thank you! Was the solution to rewrite it in Objective-C? Does apple not expose some API in C that is required to do the disassociation?

working for me too on 15.2! Thanks @shilch!

**Comment by blakegonzales** [comment]
> > @shilch Confirmed it works 15.2! Thank you! Was the solution to rewrite it in Objective-C? Does apple not expose some API in C that is required to do the disassociation?
> 
> working for me too on 15.2! Thanks @shilch!

works for me too in 15.2 :)

**Comment by mellbratt** [comment]
v0.2-draft2 branch currently not working with a Belkin wired ethernet adapter (F2CU040) on Mac OS 15.3.1.

I get`interface_set_ether: Can't assign requested address`

**Comment by stevennt** [comment]
I'm on 15.2 (24C101) and it can't compile. 

git clone -b v0.2-draft2 https://github.com/shilch/macchanger
cd macchanger
make
macchanger.m:258:61: error: use of undeclared identifier 'kIOMainPortDefault'
    CFMutableDictionaryRef matchingDict = IOBSDNameMatching(kIOMainPortDefault, 0, name);
                                                            ^
macchanger.m:263:42: error: use of undeclared identifier 'kIOMainPortDefault'
    *iface = IOServiceGetMatchingService(kIOMainPortDefault, matchingDict);
                                         ^
2 errors generated.
make: *** [macchanger] Error 1

**Comment by DarkNero69** [comment]
INFO:    Type of interface is Wi-Fi. Will disassociate from any network.
interface_set_ether: Can't assign requested address

I can't change back to my permanent mac address at all. I've tried everything. Even rebooting my mac did nothing. This is frustrating. Turning wifi off and on didn't help either and chatgpt didn't help. 

Am i even doing it correctly anymore?:

sudo macchanger
-password-

Sudo macchanger -p en0

**Comment by tmanager22** [comment]
> INFO: Type of interface is Wi-Fi. Will disassociate from any network. interface_set_ether: Can't assign requested address
> 
> I can't change back to my permanent mac address at all. I've tried everything. Even rebooting my mac did nothing. This is frustrating. Turning wifi off and on didn't help either and chatgpt didn't help.
> 
> Am i even doing it correctly anymore?:
> 
> sudo macchanger -password-
> 
> Sudo macchanger -p en0

any update on this

**Comment by shilch** [comment]
@DarkNero69 @tmanager22 Could you provide more information on this? Are you sure your current mac address is not, in fact, the permanent address?

**Comment by shilch** [comment]
Hi everyone, I merged version 0.2 to master now. Furthermore, macchanger can now be installed via brew:

```
brew install macchanger
```

As the patch for 14.4+ is now integrated into the main version, I'll be closing this issue.
